/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MROSAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/mros/mros/parser/antlr/internal/InternalMROS.tokens");
	}
}
