/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMROSScopeProvider extends DelegatingScopeProvider {
}
