/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.mros.mros.ui.internal.MrosActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MROSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(MrosActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		MrosActivator activator = MrosActivator.getInstance();
		return activator != null ? activator.getInjector(MrosActivator.ORG_XTEXT_MROS_MROS_MROS) : null;
	}

}
