/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MROSUiModule extends AbstractMROSUiModule {

	public MROSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
