/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.mros.mros.mROS.MROSPackage;
import org.xtext.mros.mros.mROS.Narowness;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Narowness</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NarownessImpl extends EnvironmentParameterImpl implements Narowness
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NarownessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MROSPackage.Literals.NAROWNESS;
  }

} //NarownessImpl
