/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mros.mros.mROS.Action#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.Action#getI <em>I</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.Action#getAt <em>At</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.Action#getQ <em>Q</em>}</li>
 * </ul>
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.Action#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' containment reference.
   * @see #setI(Parameter)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getAction_I()
   * @model containment="true"
   * @generated
   */
  Parameter getI();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.Action#getI <em>I</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' containment reference.
   * @see #getI()
   * @generated
   */
  void setI(Parameter value);

  /**
   * Returns the value of the '<em><b>At</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>At</em>' containment reference.
   * @see #setAt(ActionType)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getAction_At()
   * @model containment="true"
   * @generated
   */
  ActionType getAt();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.Action#getAt <em>At</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>At</em>' containment reference.
   * @see #getAt()
   * @generated
   */
  void setAt(ActionType value);

  /**
   * Returns the value of the '<em><b>Q</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mros.mros.mROS.QualityModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Q</em>' containment reference list.
   * @see org.xtext.mros.mros.mROS.MROSPackage#getAction_Q()
   * @model containment="true"
   * @generated
   */
  EList<QualityModel> getQ();

} // Action
