/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mros.mros.mROS.Component#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.Component#isObservable <em>Observable</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.Component#getP <em>P</em>}</li>
 * </ul>
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getComponent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.Component#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Observable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observable</em>' attribute.
   * @see #setObservable(boolean)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getComponent_Observable()
   * @model
   * @generated
   */
  boolean isObservable();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.Component#isObservable <em>Observable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Observable</em>' attribute.
   * @see #isObservable()
   * @generated
   */
  void setObservable(boolean value);

  /**
   * Returns the value of the '<em><b>P</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mros.mros.mROS.Configuration}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' containment reference list.
   * @see org.xtext.mros.mros.mROS.MROSPackage#getComponent_P()
   * @model containment="true"
   * @generated
   */
  EList<Configuration> getP();

} // Component
