/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feedback</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mros.mros.mROS.Feedback#getFeedback <em>Feedback</em>}</li>
 * </ul>
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getFeedback()
 * @model
 * @generated
 */
public interface Feedback extends EObject
{
  /**
   * Returns the value of the '<em><b>Feedback</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Feedback</em>' containment reference.
   * @see #setFeedback(MessageDefinition)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getFeedback_Feedback()
   * @model containment="true"
   * @generated
   */
  MessageDefinition getFeedback();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.Feedback#getFeedback <em>Feedback</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Feedback</em>' containment reference.
   * @see #getFeedback()
   * @generated
   */
  void setFeedback(MessageDefinition value);

} // Feedback
