/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>INPROGRESS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getINPROGRESS()
 * @model
 * @generated
 */
public interface INPROGRESS extends ResultType
{
} // INPROGRESS
