/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;

import java.lang.String;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Quality Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mros.mros.mROS.QualityModel#getQa <em>Qa</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.QualityModel#getQvalue <em>Qvalue</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.QualityModel#getE <em>E</em>}</li>
 * </ul>
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getQualityModel()
 * @model
 * @generated
 */
public interface QualityModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Qa</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qa</em>' containment reference.
   * @see #setQa(QualityAttribute)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getQualityModel_Qa()
   * @model containment="true"
   * @generated
   */
  QualityAttribute getQa();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.QualityModel#getQa <em>Qa</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qa</em>' containment reference.
   * @see #getQa()
   * @generated
   */
  void setQa(QualityAttribute value);

  /**
   * Returns the value of the '<em><b>Qvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qvalue</em>' attribute.
   * @see #setQvalue(String)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getQualityModel_Qvalue()
   * @model
   * @generated
   */
  String getQvalue();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.QualityModel#getQvalue <em>Qvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qvalue</em>' attribute.
   * @see #getQvalue()
   * @generated
   */
  void setQvalue(String value);

  /**
   * Returns the value of the '<em><b>E</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E</em>' containment reference.
   * @see #setE(Environment)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getQualityModel_E()
   * @model containment="true"
   * @generated
   */
  Environment getE();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.QualityModel#getE <em>E</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E</em>' containment reference.
   * @see #getE()
   * @generated
   */
  void setE(Environment value);

} // QualityModel
