/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Result Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mros.mros.mROS.ResultDefinition#getResult <em>Result</em>}</li>
 * </ul>
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getResultDefinition()
 * @model
 * @generated
 */
public interface ResultDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Result</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result</em>' containment reference.
   * @see #setResult(MessageDefinition)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getResultDefinition_Result()
   * @model containment="true"
   * @generated
   */
  MessageDefinition getResult();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.ResultDefinition#getResult <em>Result</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Result</em>' containment reference.
   * @see #getResult()
   * @generated
   */
  void setResult(MessageDefinition value);

} // ResultDefinition
