/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;

import java.lang.String;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skill Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.mros.mros.mROS.SkillDefinition#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.SkillDefinition#getListqa <em>Listqa</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.SkillDefinition#getP <em>P</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.SkillDefinition#getResult <em>Result</em>}</li>
 *   <li>{@link org.xtext.mros.mros.mROS.SkillDefinition#getRealizations <em>Realizations</em>}</li>
 * </ul>
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getSkillDefinition()
 * @model
 * @generated
 */
public interface SkillDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.mros.mros.mROS.MROSPackage#getSkillDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.mros.mros.mROS.SkillDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Listqa</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mros.mros.mROS.QualityAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Listqa</em>' containment reference list.
   * @see org.xtext.mros.mros.mROS.MROSPackage#getSkillDefinition_Listqa()
   * @model containment="true"
   * @generated
   */
  EList<QualityAttribute> getListqa();

  /**
   * Returns the value of the '<em><b>P</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mros.mros.mROS.ParameterType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>P</em>' containment reference list.
   * @see org.xtext.mros.mros.mROS.MROSPackage#getSkillDefinition_P()
   * @model containment="true"
   * @generated
   */
  EList<ParameterType> getP();

  /**
   * Returns the value of the '<em><b>Result</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mros.mros.mROS.ResultType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result</em>' containment reference list.
   * @see org.xtext.mros.mros.mROS.MROSPackage#getSkillDefinition_Result()
   * @model containment="true"
   * @generated
   */
  EList<ResultType> getResult();

  /**
   * Returns the value of the '<em><b>Realizations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.mros.mros.mROS.SkillRealization}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Realizations</em>' containment reference list.
   * @see org.xtext.mros.mros.mROS.MROSPackage#getSkillDefinition_Realizations()
   * @model containment="true"
   * @generated
   */
  EList<SkillRealization> getRealizations();

} // SkillDefinition
