/**
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.mROS;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.mros.mros.mROS.MROSPackage#getString()
 * @model
 * @generated
 */
public interface String extends EObject
{
} // String
