/*
 * generated by Xtext 2.21.0
 */
package org.xtext.mros.mros.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.mros.mros.MROSRuntimeModule;
import org.xtext.mros.mros.MROSStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MROSIdeSetup extends MROSStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MROSRuntimeModule(), new MROSIdeModule()));
	}
	
}
